name: Run the unit tests
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./github/actions/install-dependecies.yml
      
      - name: Run pytest
        run: pytest

  runmigration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./github/actions/install-dependecies.yml
      
      - name: Run django migrate
        run: python manage.py migrate
  
  migrations-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./github/actions/install-dependecies.yml

      - name: Run makemigrations
        run: python manage.py makemigrations --check

  build-docker-image:
    runs-on: ubuntu-latest

    needs:
      - test
      - runmigration
      - migrations-check

    if: github.ref == 'refs/head/main'

    permissions:
      contents: read
      packagess: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker meta
        id: meta
        uses:  docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Build and push
        uses:  docker/build-push-action@v6
        with:
          context: .
          tags: ${{steps.meta.outputs.tags}}
          push: true
          labels: ${{steps.meta.outputs.labels}}


      



