name: Run the unit tests
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./github/actions/install-dependecies
      
      - name: Run pytest
        run: pytest

  runmigration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./github/actions/install-dependecies
      
      - name: Run django migrate
        run: python manage.py migrate
  
  migrations-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./github/actions/install-dependecies
      
      - name: Run makemigrations
        run: python manage.py makemigrations --check


